[package]
name = "collatz_app"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["canvas", "image", "tokio"] }
iced_native = "0.10"
plotters = "0.3"
plotters-backend = "0.3"
plotters-iced = "0.8"
rand = "0.8"
image = "0.24"
clipboard = "0.5"
chrono = "0.4"
